services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper


# services:
#   zookeeper:
#     image: zookeeper
#     hostname: zookeeper
#     ports:
#       - 2181:2181
#     environment:
#       - ALLOW_ANONYMOUS_LOGIN=yes
#   kafka:
#     restart: always
#     image: ches/kafka
#     hostname: localhost
#     ports:
#       - "9092:9092"
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ADVERTISED_HOST_NAME: Blockchain
#       ZOOKEEPER_IP: zookeeper:2181
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#       ALLOW_PLAINTEXT_LISTENER: 1
    
#     depends_on:
#       - zookeeper